#ifndef DATA_SOURCE_HPP
#define DATA_SOURCE_HPP

//!< Source for input data.  Data is either in sensorgnome format, from a file or stream,
//!< or in Lotek format (generated by wrapper code in the motus R package)

#include "find_tags_common.hpp"

using boost::serialization::make_nvp;


class Data_Source { 

public:
  Data_Source();
  ~Data_Source();

  virtual bool getline(char * buf, int maxLen) = 0;

  virtual void serialize(boost::archive::binary_iarchive & ar, const unsigned int version){};

  virtual void serialize(boost::archive::binary_oarchive & ar, const unsigned int version){};

};

#endif // DATA_SOURCE
