#ifndef DATA_SOURCE_HPP
#define DATA_SOURCE_HPP

//!< Source for input data.  Data is either in sensorgnome format, from a file or stream,
//!< or in Lotek format (generated by wrapper code in the motus R package)

#include "find_tags_common.hpp"

class Data_Source { 

public:
  Data_Source();
  ~Data_Source();

virtual bool getline(char * buf, int maxLen) = 0;

};

#endif // DATA_SOURCE
